SogWebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from sogapp import views
urlpatterns = [
	url(r'^$', views.index, name='index' ),
    url(r'^admin/', admin.site.urls),
    url(r'', include('sogapp.urls')), #Urls for sogs website

  ]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sogapp/urls.py
from django.conf.urls import url
from . import views

app_name = "sogapp"
urlpatterns =[
	# url(r'^about', views.about, name="about"),
	url(r'^recording/artists/$', views.recording_artist_view, name="recording_artist_view"),
	url(r'^music/release/$', views.music_release, name="music_release"),
	url(r'^music/shows/$', views.upcommingshows, name="upcommingshows"),
	url(r'^music/contact/page/$', views.contact_view, name="contact_view"),
	url(r'^music/thanks/page/$', views.thanks_view, name="thanks_view"),
	url(r'^music/artist/profile/(?P<pk>\d+)/$', views.artist_details, name="artist_details")

]

sogapp/models.py
from django.db import models

# Create your models here.
# This is the user contact model form for this website.
class UserContactInfo(models.Model):
    first_name = models.CharField(max_length=250, blank=False)
    last_name = models.CharField(max_length=250, blank=False)
    email = models.CharField(max_length=250, blank=False)
    message = models.TextField(blank=False)

    def __str__(self):
        return self.first_name +" "+ self.last_name

class ArtistInfo(models.Model):
    first_name = models.CharField(max_length=150, blank=False)
    last_name = models.CharField(max_length=250, blank=False)
    artist_bio = models.TextField(blank=False)
    artist_photo1_url = models.URLField(blank=False)
    artist_photo2_url = models.URLField(blank=False)
    artist_photo3_url = models.URLField(blank=False)

    def __str__(self):
        return self.first_name + " "+ self.last_name

sogapp/forms.py
from django import forms 
from . models import UserContactInfo

# The user contact form for this website.
class UserContactForm(forms.ModelForm):
    class Meta:
        model = UserContactInfo
        fields = ('first_name', 'last_name', 'email', 'message')

sogapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . forms import UserContactForm
from .models import ArtistInfo

# Create your views here.

app_name = 'sogapp'
def index(request):
	return render(request, "sogapp/index.html")


def recording_artist_view(request):
	artist_info = ArtistInfo.objects.all()
	return render(request, "sogapp/recording_artist.html", {"artist_info": artist_info})


def music_release(request):
	return render(request, "sogapp/music_release.html")

def upcommingshows(request):

	return render(request, "sogapp/shows.html")

def contact_view(request):
    if request.method == "POST":
        print("Hello")
        form = UserContactForm(request.POST or None)
        if form.is_valid():
            form_data = form.save(commit=False)
            print(form_data.first_name)
            form.save()
            return redirect('sogapp:thanks_view')
    else:
        form = UserContactForm()
        return render(request, 'sogapp/contact.html', {'form':form})

def thanks_view(request):
    return render(request, "sogapp/thanks.html")


def artist_details(request, pk):
	artist_info = get_object_or_404(ArtistInfo, pk=pk);
	return render(request, 'sogapp/artist_detail_info.html', {"artist_info":artist_info})

templates/sogapp/artist_detail_info.html
{% extends 'sogapp/base.html' %}
{% load static %}
{% block title %}
<title>{{artist_info.first_name}} {{artist_info.last_name}} Profile</title>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row top_padding">
    <h4>{{artist_info.first_name}} {{artist_info.last_name}} Profile</h4>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
      <div class="slideshow pull-left">
        <img class="thumbnail" src="{{artist_info.artist_photo1_url}}" width="450" height="400" />
        <img class="thumbnail" src="{{artist_info.artist_photo2_url}}" width="450" height="400" />
        <img class="thumbnail" src="{{artist_info.artist_photo3_url}}" width="450" height="400" />
    </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 ">
      <div class="artist_bio pull-right">
        <h3>Biography</h3>
        <p>{{artist_info.artist_bio}}</p>
      </div>

    </div>
</div>
</div>
{% include 'sogapp/backgroundslideshow/slideshow.html' %}
{% include 'sogapp/footer/footer.html' %}
{% endblock %}

templates/sogapp/backgroundslideshow/slideshow.html
<div id="slideshow">
  <img src="https://source.unsplash.com/wN1CH6Ferbg" class="bgM img-responsive"/>
  <img src="https://source.unsplash.com/B7kmxOytq0g" class="bgM img-responsive"/>
  <img src="https://source.unsplash.com/CbeIuWOVcvY" class="bgM img-responsive"/>
  <img src="https://source.unsplash.com/Qrspubmx6kE" class="bgM img-responsive"/>
</div>

templates/sogapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Archivo+Black|Boogaloo|Bowlby+One|Cherry+Cream+Soda|Days+One|Great+Vibes|Mogra|Pangolin|Permanent+Marker|Russo+One|Shrikhand" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/semantic.min.css">
{% block styles %}
  <link href="{% static "/css/sog.css" %}" rel="stylesheet">
  <link href="{% static "/css/footer.css" %}" rel="stylesheet">
    <link href="{% static "/sogapp/css/carousel.css" %}" rel="stylesheet">
{% endblock styles %}
{% block title %}
	<title></title>
{% endblock %}
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand"href={% url "index" %}>SOG Records</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href={% url 'index' %}><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
        <li><a href={% url 'sogapp:recording_artist_view' %}><i class="fa fa-user-circle" aria-hidden="true"></i> Artists</a></li>
        <li><a href={% url 'sogapp:music_release' %}><i class="fa fa-music" aria-hidden="true"></i> Songs</a></li>
        <li><a href={% url "sogapp:upcommingshows" %}><i class="fa fa-calendar"></i> Events</a></li>
        <li ><a href={% url "sogapp:contact_view" %}><i class="fa fa-address-book-o" aria-hidden="true"></i> Contact</a></li>
      </ul>
    </div>
  </nav>

{% block content %}
<!-- Background images for background slideshow -->
  {% include 'sogapp/backgroundslideshow/slideshow.html' %}
  <!-- Carousel of the home page -->
  {% include 'sogapp/carousel/carousel.html' %}
  <!-- Intro text on the home page -->
    {% include 'sogapp/intro.html' %}
    <!-- footer of the website -->
{% include 'sogapp/footer/footer.html' %}
{% endblock %}
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
  <!-- <script type="text/javascript" src="{% static "js/jquerycircleplugin.js" %}"></script> -->
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.cycle/3.0.3/jquery.cycle.all.min.js"></script>
<script type="text/javascript" src="{% static "js/artist.js" %}"></script>
</body>
</html>

templates/sogapp/carousel/carousel.html
{% load staticfiles %}
<!-- End of Navigation -->
  <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="9000">
    <ol class="carousel-indicators">
      <li data-target='#myCarousel' data-slide-to="0" li>
      <li data-target='#myCarousel' data-slide-to="1" class="active"></li>
      <li data-target='#myCarousel' data-slide-to="2" ></li>
    </ol>
    <div class="carousel-inner">
      <div class="item active">
        <img src="http://res.cloudinary.com/dypjectne/image/upload/c_scale,h_760,w_760/v1497841854/cicConcert_qrmiic.jpg" alt="">
        <div class="container active">
          <div class="carousel-caption">
            <h1></h1>
            <p class="artist_intro"></p>
          </div>
        </div>
      </div>
      <div class="item">
        <img src="http://res.cloudinary.com/dypjectne/image/upload/c_fill,h_960,q_98,w_960/v1497832812/SOG_Pray_s5f5dv.png" alt="">
        <div class="container active">
          <div class="carousel-caption">
            <h1></h1>
            <p class="artist_intro"></p>
          </div>
        </div>
      </div>
      <div class="item">
        <img src="http://res.cloudinary.com/dypjectne/image/upload/v1497832804/CICDengG_nu6uu0.png" alt="">
        <div class="container active">
          <div class="carousel-caption">
            <h1></h1>
            <p class="artist_intro"></p>
          </div>
        </div>
      </div>
    </div>
    <a href="#myCarousel" class="left carousel-control" data-slide='prev'><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a href="#myCarousel" class="right carousel-control" data-slide='next'><span class="glyphicon glyphicon-chevron-right"></span></a>
  </div>

templates/sogapp/contact.html
{% extends 'sogapp/base.html' %}
{% load static %}
{% block title %}
<title>Contact Page</title>
{% endblock %}
{% load crispy_forms_tags %}


{% block content %}

<!-- End of Navigation -->
  <div class="intro-block">
    <div class="container">

      <div class="row">
        <div class="col-xs-12 col-md-8 col-lg-8 col-sm-12 contact">
          <h1>SOG Records Empire <span class="text-muted">&raquo; Contact Us</span>
          </h1>
          <p class="lead intro">Do you want to know more about SOG Records Empire and how we can help take your career and music to the next level? Don't hesistate to send us information by filling out our contact form below. Are you looking for a management that will put career first in everything that we do? If your answer is yes, then wait no more because SOG Record Empire is here to make your dreams come true.</p>
        </div>
        <div class="col-xs-12 col-sm-12 col-lg-4 col-md-4">
        <img class="img-responsive img-circle" src="{% static "images/SOGLOGO.jpg" %}">

        </div>
      </div>
    </div>
  </div>

  <div class="map" style="width:350; ">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3965.6771911294654!2d-10.801062584621693!3d6.306074327400786!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xf09f81d4b7be221%3A0x9279760aa34e25b4!2sCamp+Johnson+Rd%2C+Monrovia%2C+Liberia!5e0!3m2!1sen!2sus!4v1496200422529"

    width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>

  <!-- End Intro Text-->
  <div class="container">
    <div class="row">
      <div class="col-sm-12 get_in_touch">
        <h2><strong>Get in touch</strong></h2><hr>
        <p class="intro">Want to learn more about the exciting opportunities we have at SOG Records Empire. If you have any questions, contact us and we'll be glad to anwer them.
        Get in touch my filling out the below form. We get back to you within the next 24hrs. <strong>SOG Records</strong> wants to hear for you: </p>
          <form method="POST" class="contact_form">
                   {% csrf_token %}
          {{form|crispy}}
          <input class="btn btn-primary btn-lg" type="submit" name="" value="send message">
          <br><br>
        </form>
        </div>
      </div>
    </div>

  </div>

{% include 'sogapp/footer/footer.html' %}
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  {% include 'sogapp/backgroundslideshow/slideshow.html' %}

{% endblock %}

templates/sogapp/footer/footer.html
  {% load staticfiles %}
  <div class="container">
    <div class="row">
      <hr>
      <div class="col-xs-12 col-sm-4 col-lg-4 col-md-4 footer_text">
        <footer>
            <address >
              <h2>SOG Records Empire</h2>
              Camp Johnson Road <br>
              Monrovia, Liberia 1000-10 <br>
              West African, Africa <br>
              <a href="mailto: contact@sogrecordsempire.com">contact@sogrecordsempire.com</a><br>
              <abbr title="Phone">P:</abbr>+231886205927
            </address>
              </footer>
            <div class="social footer_text">
            <h2>Get Connected</h2>
            <a href="https://twitter.com/SOGMARKET" target="_blank" class="twitter"><i class="fa fa-twitter fa-3x" aria-hidden="true"></i></a>

            <a href="https://www.facebook.com/SOGRECORDSEMPIRE/" target="_blank" class="facebook"><i class="fa fa-facebook fa-3x" aria-hidden="true"></i></a>

            <a href="https://www.youtube.com/channel/UCVEZoCS5Xrz2F5e9ZQIE5ng" target="_blank" class="youtube"><i class="fa fa-youtube fa-3x" aria-hidden="true"></i></a>

              <a href="https://www.instagram.com/sogrecordsempire/?hl=en" target="_blank" class="instagram"><i class="fa fa-instagram fa-3x" aria-hidden="true"></i></a>
          </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-lg-4 col-md-4 footer_text">
        <blockquote cite="http://"><p>&ldquo;SOG Records has completely revolunized Liberian music for the better. Considering SOG as you record label, you will be linked to the world of endless possibilities
           and opportunities.</p>
              <p>At SOG Records Empire, we are dedicated to making all artists achieve their full
             potential trhough the provision of mentorship and musical support.&rdquo;</p>
           <p><small>King Jaffar, <cite title="source title">SOG Records</cite></small>
         </blockquote></p>
      </div>

      <div class="col-sm-4 col-xs-6 col-md-4 col-lg-4 hidden-xs footer_text">
        <img  class="img-responsive jaffar img-circle" src="http://res.cloudinary.com/dypjectne/image/upload/v1496462716/KingJaffar_tgsydf.jpg" %}>
        <div class="copyright">
          <p>&copy; 2017 SOG Records Empire</p>
        </div>
      </div>
    </div>
  </div>

templates/sogapp/index.html
{% extends 'sogapp/base.html' %}

{% block title %}
	<title>SOG Records</title>
{% endblock %}

templates/sogapp/intro.html
 {% load staticfiles %}
 <div class="intro-block">
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 hidden-xs tpad">
          <img class="img-responsive img-circle" src={% static "images/SOGLOGO.jpg" %} alt="">
        </div>
        <div class="col-xs-12 col-sm-9 col-lg-9 col-md-9 tpad">
<iframe name="full" style="width:100%;height:520px;border:0px;" src="//widget.cdbaby.com/3cbe9e11-19cf-48f3-bac3-86c80b5d31c7/full/light/opaque"></iframe>
          <h1>SOG RECORDS <span class="text-muted">&raquo; Sounds of Greatness<i class="fa fa-music"><i class="fa fa-music"></i></i></span>
          </h1>
          <p>SOG Records Empire is an outstanding record label that you can entrust with your career. SOG Records Empire is primarily founded on the basis of promoting and elevating talents of recording artists to the next level. We produced musics that entertained and energized our fans and clients. We worked with artists from diverse background, because we strongly believe in providing opportunity to every unique talent that comes by. We wholeheartedly take our fans and artist very essential. Without them, our existence as a record label will not be a reality.Pomoting and elevating Liberian and world talents is at the core value of our work. We appreciate our relationship with our cleints, fans and artists.  Without you, we wouldn't be where we are today.
             We are here to help promote Liberian and world talents. </p>
        </div>
      </div>
    </div>
  </div>

templates/sogapp/music_release.html
{% extends 'sogapp/base.html' %}
{% load static %}

{% block title %}
<title>Music Release</title>
{% endblock %}
		{% block content %}
		<div class="container music_release">
		<h1>Music Release</h1>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
			<div class="caption">
				<h4>Music Title: Musu</h4>
			</div>
				<!-- 16:9 aspect ratio -->
				<div class="embed-responsive embed-responsive-16by9">
				  <iframe height="500" class="embed-responsive-item" src="https://www.youtube.com/embed/TWzZeWcmzwY?ecver=2">

				  </iframe>

				</div>
			</div>

			<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 youtube">
			<div class="caption">
				<h4>Music Title: In the Pool</h4>
			</div
				<!-- 16:9 aspect ratio -->
				<div class="embed-responsive embed-responsive-16by9">
				  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/s2cBEmzzZ-o?ecver=2">

				  </iframe>

				</div>
			</div>

			<div class="col-xs-12 col-xs-12 col-md-6 col-lg-6 youtube">
			<div class="caption">
				<h4>Music Title: Jammay</h4>
			</div
				<!-- 16:9 aspect ratio -->
				<div class="embed-responsive embed-responsive-16by9">
				  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/2Yx_qpRwEjk?ecver=2">

				  </iframe>

				</div>
			</div>

			<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 youtube">
			<div class="caption">
				<h4>Music Title: Grateful</h4>
			</div
				<!-- 16:9 aspect ratio -->
				<div class="embed-responsive embed-responsive-16by9">
				  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/VqCu0r9S5EI?ecver=2">

				  </iframe>

				</div>
			</div>
			<div class="col-xs-12 col-md-6 col-sm-12 col-lg-6 youtube">
			<div class="caption">
				<h4>Music Title: I Tell You</h4>
			</div
				<!-- 16:9 aspect ratio -->
				<div class="embed-responsive embed-responsive-16by9">
				  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/J-OnrmtC_Aw?ecver=2">

				  </iframe>
				</div>
			</div>
			<div class="col-xs-12 col-md-6 col-lg-6 col-sm-12 youtube">
			<div class="caption">
				<h4>Music Title: Last Bus Stop</h4>
			</div
				<!-- 16:9 aspect ratio -->
				<div class="embed-responsive embed-responsive-16by9">
				  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/S4eQumKL4k0?ecver=2">

				  </iframe>

				</div>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 youtube">
			<div class="caption">
				<h4>Music Title: In My Head</h4>
			</div
				<!-- 16:9 aspect ratio -->
				<div class="embed-responsive embed-responsive-16by9">
				  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/SoaSzi5OstI?ecver=2">

				  </iframe>

				</div>
			</div>
			<div class="col-xs-12 col-md-6 col-sm-12 col-lg-6 youtube">
			<div class="caption">
				<h4>Music Title: Mary Go Round</h4>
			</div
				<!-- 16:9 aspect ratio -->
				<div class="embed-responsive embed-responsive-16by9">
				  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ERP20tE1J50?ecver=2">

				  </iframe>

				</div>
			</div>

		</div>
</div>


	  {% include 'sogapp/backgroundslideshow/slideshow.html' %}
	  {% include 'sogapp/footer/footer.html' %}
{% endblock content %}

templates/sogapp/recording_artist.html
{% extends 'sogapp/base.html' %}
{% load static %}
{% block title %}
<title>Recording Artist</title>
{% endblock %}
{% block content %}
{% include 'sogapp/backgroundslideshow/slideshow.html' %}
<div class="container top_padding">
	<h1>Recording Artists</h1>
	<div class="row"style="display: flex; flex-wrap: wrap" class="">
	  {% for artist in artist_info %}
		<div class="col-xs-12 col-lg-4 col-md-4 col-sm-4">
			<div class="thumbnail enlarge">
      <img src="{{artist.artist_photo1_url}}" alt="{{artist.first_name}}">
      <div class="caption">
        <h4>Name: {{artist.first_name}} {{artist.last_name}}</h4>
        <p>{{artist.artist_bio|truncatechars:100}}</p>
        <p><a href="{% url 'sogapp:artist_details' pk=artist.pk %}" class="btn btn-primary btn-lg" role="button">Read Artist Profile</a></p>
      </div>
    	</div>
		</div>
		{% endfor %}
	</div>

	{% include 'sogapp/footer/footer.html' %}
</div>
{% endblock %}

templates/sogapp/shows.html
{% extends 'sogapp/base.html' %}

{% block title %}
	<title>SOG Records</title>
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 100px;">
<h1>No event available at this time</h1>
</div>

{% endblock %}

templates/sogapp/thanks.html
{% extends 'sogapp/base.html' %}
<html>
{% block title %}
	<title>SOG Records</title>
{% endblock %}
{% block content %}
	<div class="container" style="margin-top: 50px; color:white;">
	<h1>Thanks for sending us a message. We will reply to your email in the next 24hrs.</h1>

<a href={% url "index" %} class="btn btn-primary">Return to Home page</a>
</div>
{% include 'sogapp/backgroundslideshow/slideshow.html' %}
{% include 'sogapp/footer/footer.html' %}
{% endblock content %}